// library must be configured (configure system / Global Pipeline Libraries)
// https://forge.dgfip.finances.rie.gouv.fr/dgfip/drupal-php/components/jenkins/sdp-jenkins-libs.git

@Library('sdplib') _
libraryScriptedTest('project': 'TestLogger', 'sonarExclusion': '**LogTestCase**', 'images': [ 'php81'])
