name: lint

on: [push, pull_request]

jobs:

  phpcs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.0, 8.1]
    steps:
      - uses: actions/checkout@v2
      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
      - name: install dependencies
        run: |
          composer install
      - run: composer run phpcs

  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.0, 8.1]
    steps:
      - uses: actions/checkout@v2
      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          coverage: xdebug
      - name: install dependencies
        run: |
          composer install
      - run: composer run phpstan

